language: php

php:
# aliased to a recent 7.x version
  - 7.1.32
services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.0-trusty
    packages:
      - mysql-server

dist: trusty

before_install:
  - mysql -u root --password="" < bodega/simple_stock.sql

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_mysql.xml --coverage-text