language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1.32
      env: WITH_COVERAGE=true
# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

before_script:

  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS simple_stock;" -uroot; fi

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_mysql.xml --coverage-text