language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1.32
      env: WITH_COVERAGE=true


before_script:

- composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "CREATE DATABASE simple_stock" -uroot

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_mysql.xml --coverage-text