language: php

php:
# aliased to a recent 7.x version
  - 7.1.32
services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.0.12-trusty
    packages:
      - mysql-server

dist: trusty

before_script:

  -  mysql -e "create database IF NOT EXISTS simple_stock;";

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_mysql.xml --coverage-text