language: php

# aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm
  

before_script:

  -  mysql -e "create database IF NOT EXISTS simple_stock;" -uroot;

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_mysql.xml --coverage-text