language: php

php:
# aliased to a recent 7.x version
  - 7.2
services:
  - mysql

before_install:
  - mysql -u root --password="" < bodega/simple_stock.sql

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_mysql.xml 

# Here is the magic part
deploy:
  # Use Github pages deploy process
  provider: pages:git
  # Directory where your generated files are located
  local_dir: public
  # Github security/auth token
  token: bbf1884ca922e9a46423587dd70881f1be5d4f74
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  edge: true # opt in to dpl v2
  on:
    # Which branch on commit/push will trigger deployment
    branch: main